module.exports = {
  colors: {
    AL: {
      fill: 'grey',
    },
    AK: {
      fill: 'grey',
    },
    AZ: {
      fill: 'grey',
    },
    AR: {
      fill: 'grey',
    },
    CA: {
      fill: 'grey',
    },
    CO: {
      fill: 'grey',
    },
    CT: {
      fill: 'grey',
    },
    DC: {
      fill: '#0158f8',
    },
    DE: {
      fill: 'grey',
    },
    FL: {
      fill: 'grey',
    },
    GA: {
      fill: 'grey',
    },
    HI: {
      fill: 'grey',
    },
    ID: {
      fill: 'grey',
    },
    IL: {
      fill: 'grey',
    },
    IN: {
      fill: 'grey',
    },
    IA: {
      fill: 'grey',
    },
    KS: {
      fill: 'grey',
    },
    KY: {
      fill: 'grey',
    },
    LA: {
      fill: 'grey',
    },
    ME: {
      fill: 'grey',
    },
    MD: {
      fill: 'grey',
    },
    MA: {
      fill: 'grey',
    },
    MI: {
      fill: 'grey',
    },
    MN: {
      fill: 'grey',
    },
    MS: {
      fill: 'grey',
    },
    MO: {
      fill: 'grey',
    },
    MT: {
      fill: 'grey',
    },
    NE: {
      fill: 'grey',
    },
    NV: {
      fill: 'grey',
    },
    NH: {
      fill: 'grey',
    },
    NJ: {
      fill: 'grey',
    },
    NM: {
      fill: 'grey',
    },
    NY: {
      fill: 'grey',
    },
    NC: {
      fill: 'grey',
    },
    ND: {
      fill: 'grey',
    },
    OH: {
      fill: 'grey',
    },
    OK: {
      fill: 'grey',
    },
    OR: {
      fill: 'grey',
    },
    PA: {
      fill: 'grey',
    },
    RI: {
      fill: 'grey',
    },
    SC: {
      fill: 'grey',
    },
    SD: {
      fill: 'grey',
    },
    TN: {
      fill: 'grey',
    },
    TX: {
      fill: 'grey',
    },
    UT: {
      fill: 'grey',
    },
    VT: {
      fill: 'grey',
    },
    VA: {
      fill: 'grey',
    },
    WA: {
      fill: 'grey',
    },
    WV: {
      fill: 'grey',
    },
    WI: {
      fill: 'grey',
    },
    WY: {
      fill: 'grey',
    },
  },
  TX: {
    'Total Filings': 22,
    'Madison v. Alabama': 1,
    'Garza v. Idaho': 1,
    'Virginia Uranium v. Warren': 1,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': -1,
    'McDonough v. Smith': 1,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 1,
    'Carpenter v. Murphy': -1,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': -1,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 1,
    'Washington State Department of Licensing v. Cougar Den Inc.': -1,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': -1,
  },
  LA: {
    'Total Filings': 22,
    'Madison v. Alabama': 1,
    'Garza v. Idaho': 1,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': -1,
    'McDonough v. Smith': 1,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 1,
    'Carpenter v. Murphy': -1,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': -1,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': 1,
    'Washington State Department of Licensing v. Cougar Den Inc.': -1,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  IN: {
    'Total Filings': 21,
    'Madison v. Alabama': 1,
    'Garza v. Idaho': 1,
    'Virginia Uranium v. Warren': 1,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': -1,
    'McDonough v. Smith': 1,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': -1,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': 1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  NE: {
    'Total Filings': 17,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 1,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': -1,
    'McDonough v. Smith': 1,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 1,
    'Carpenter v. Murphy': -1,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': -1,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': -1,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  SC: {
    'Total Filings': 17,
    'Madison v. Alabama': 1,
    'Garza v. Idaho': 1,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 1,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': -1,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': -1,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  OK: {
    'Total Filings': 16,
    'Madison v. Alabama': 1,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': -1,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': 1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': -1,
  },
  AR: {
    'Total Filings': 16,
    'Madison v. Alabama': 1,
    'Garza v. Idaho': 1,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 1,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': -1,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': 1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  KS: {
    'Total Filings': 15,
    'Madison v. Alabama': 1,
    'Garza v. Idaho': 1,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 1,
    'Carpenter v. Murphy': -1,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': -1,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': -1,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  GA: {
    'Total Filings': 14,
    'Madison v. Alabama': 1,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  UT: {
    'Total Filings': 14,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 1,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': -1,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': 1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  AL: {
    'Total Filings': 13,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 1,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  MI: {
    'Total Filings': 13,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': -1,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  ID: {
    'Total Filings': 13,
    'Madison v. Alabama': 1,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': -1,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': -1,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  SD: {
    'Total Filings': 12,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 1,
    'Carpenter v. Murphy': -1,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': -1,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': -1,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  RI: {
    'Total Filings': 12,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 1,
    'Virginia Uranium v. Warren': 1,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': -1,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  CO: {
    'Total Filings': 12,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  WY: {
    'Total Filings': 11,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 1,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': -1,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': -1,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': -1,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  OH: {
    'Total Filings': 11,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 1,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  MT: {
    'Total Filings': 11,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': -1,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': -1,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  CA: {
    'Total Filings': 10,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 1,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 1,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': -1,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  WA: {
    'Total Filings': 10,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 1,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 1,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  FL: {
    'Total Filings': 10,
    'Madison v. Alabama': 1,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': -1,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  OR: {
    'Total Filings': 10,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 1,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 1,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': 1,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  MN: {
    'Total Filings': 10,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 1,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': 1,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  AK: {
    'Total Filings': 10,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': -1,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  ND: {
    'Total Filings': 9,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 1,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  NJ: {
    'Total Filings': 9,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 1,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 1,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  MA: {
    'Total Filings': 9,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 1,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 1,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 1,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': -1,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  MD: {
    'Total Filings': 9,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 1,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 1,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': 1,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  IA: {
    'Total Filings': 9,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  CT: {
    'Total Filings': 9,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 1,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 1,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  PA: {
    'Total Filings': 9,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 1,
    'Virginia Uranium v. Warren': 1,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': 0,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 1,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  AZ: {
    'Total Filings': 9,
    'Madison v. Alabama': 1,
    'Garza v. Idaho': 1,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': -1,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  IL: {
    'Total Filings': 8,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': -1,
    'New Prime, Inc. v. Oliveira': 1,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': 1,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  WI: {
    'Total Filings': 8,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 1,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': -1,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': -1,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  MS: {
    'Total Filings': 8,
    'Madison v. Alabama': 1,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': -1,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  NY: {
    'Total Filings': 7,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': 0,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 1,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 1,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': -1,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  WV: {
    'Total Filings': 7,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': -1,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': -1,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  VT: {
    'Total Filings': 7,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 1,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  NC: {
    'Total Filings': 7,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 1,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': 1,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  NV: {
    'Total Filings': 7,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': -1,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': -1,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 1,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  MO: {
    'Total Filings': 7,
    'Madison v. Alabama': 1,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': -1,
    'Apple v. Pepper': 1,
    'Department of Commerce v. New York': -1,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': -1,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  HI: {
    'Total Filings': 7,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 1,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': -1,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 1,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  KY: {
    'Total Filings': 7,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 1,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': -1,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  VA: {
    'Total Filings': 6,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  TN: {
    'Total Filings': 6,
    'Madison v. Alabama': 1,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': -1,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 1,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': -1,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
  ME: {
    'Total Filings': 5,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': -1,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 1,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  DE: {
    'Total Filings': 5,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': -1,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': -1,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 1,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  NM: {
    'Total Filings': 3,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 1,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': 0,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': -1,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 1,
  },
  NH: {
    'Total Filings': 0,
    'Madison v. Alabama': 0,
    'Garza v. Idaho': 0,
    'Virginia Uranium v. Warren': 0,
    'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.': 0,
    'McDonough v. Smith': 0,
    'Department of Commerce v. U.S. District Court for the Southern District of New York': 0,
    'US v. Haymond': 0,
    'Tennessee Wine & Spirits Retailers Association v. Blair': 0,
    'The American Legion v. American Humanist Association': 0,
    'Herrera v. Wyoming': 0,
    'Carpenter v. Murphy': 0,
    'Bucklew v. Precythe': 0,
    'Merck Sharp & Dohme Corp. v. Albrecht': 0,
    'Taggart v. Lorenzen': 0,
    'Sturgeon v. Frost': 0,
    'Franchise Tax Board of California v. Hyatt': 0,
    'Weyerhaeuser Company v. U.S. Fish and Wildlife Service': 0,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust': 0,
    'New Prime, Inc. v. Oliveira': 0,
    'Mitchell v. Wisconsin': 0,
    'Frank v. Gaos': 0,
    'Apple v. Pepper': 0,
    'Department of Commerce v. New York': 0,
    'Cochise Consultancy Inc. v. U.S., ex rel. Hunt': 0,
    'Rucho v. Common Cause': 0,
    'Washington State Department of Licensing v. Cougar Den Inc.': 0,
    'Kisor v. Wilkie': 0,
    'Knick v. Township of Scott, Pennsylvania': 0,
  },
};
